// ============================================================
// Horeca1 V2.2 — Mock Data for UI Development
// ============================================================

import type { Vendor, VendorProduct, Category, OrderList, PurchaseOrder, VendorSummary, BrandStore } from '@/types';

// ---- VENDORS ----

export const MOCK_VENDORS: Vendor[] = [
    {
        id: 'v1',
        name: 'Emarket',
        slug: 'emarket',
        logo: '/images/placeholders/no-vendor.svg',
        rating: 4.6,
        totalRatings: 234,
        deliverySchedule: 'Tomorrow 7:00 AM',
        deliveryTime: '24 hrs',
        minOrderValue: 500,
        creditEnabled: true,
        creditAmount: 25000,
        categories: ['Grocery', 'Vegetable', 'Cleaning'],
        isActive: true,
        description: 'Your everyday grocery and household needs.',
    },
    {
        id: 'v2',
        name: 'Whole Food Market',
        slug: 'whole-foods',
        logo: '/images/top vendors/whole-foods-market.png',
        rating: 4.8,
        totalRatings: 312,
        deliverySchedule: 'Today 4:00 PM',
        deliveryTime: '6 hrs',
        minOrderValue: 300,
        creditEnabled: true,
        creditAmount: 50000,
        categories: ['Organic', 'Fruits', 'Vegetables'],
        isActive: true,
        description: 'Organic and whole grain superstore.',
    },
    {
        id: 'v3',
        name: 'M Mart',
        slug: 'm-mart',
        logo: '/images/top vendors/m-mart.png',
        rating: 4.3,
        totalRatings: 189,
        deliverySchedule: 'Tomorrow 6:00 AM',
        deliveryTime: '18 hrs',
        minOrderValue: 1000,
        creditEnabled: false,
        categories: ['Imported', 'Frozen', 'Grocery'],
        isActive: true,
        description: 'Imported, frozen, and ready-to-eat specialists.',
    },
    {
        id: 'v4',
        name: 'Groceri',
        slug: 'groceri',
        logo: '/images/top vendors/groceri.png',
        rating: 4.2,
        totalRatings: 156,
        deliverySchedule: 'Tomorrow 5:30 AM',
        deliveryTime: '20 hrs',
        minOrderValue: 400,
        creditEnabled: true,
        creditAmount: 15000,
        categories: ['Groceries', 'Daily Essentials'],
        isActive: true,
        description: 'Complete grocery and daily essentials.',
    },
    {
        id: 'v5',
        name: 'Borcelle',
        slug: 'borcelle',
        logo: '/images/top vendors/961d17c25868145dd167df9f88ca0d40a7c057d1.png',
        rating: 4.7,
        totalRatings: 201,
        deliverySchedule: 'Tomorrow 8:00 AM',
        deliveryTime: '22 hrs',
        minOrderValue: 600,
        creditEnabled: true,
        creditAmount: 30000,
        categories: ['Grocery', 'Dry Fruits', 'Organic'],
        isActive: true,
        description: 'Organic and dry fruits specialists.',
    },
    {
        id: 'v6',
        name: 'Cartomart',
        slug: 'cartomart',
        logo: '/images/top vendors/39a5dd37096e44eb8b72e053055e32896d63c44a.png',
        rating: 4.4,
        totalRatings: 98,
        deliverySchedule: 'Tomorrow 10:00 AM',
        deliveryTime: '24 hrs',
        minOrderValue: 750,
        creditEnabled: false,
        categories: ['Grocery'],
        isActive: true,
        description: 'Fresh grocery delivered daily.',
    },
    {
        id: 'v7',
        name: 'Mentari Mart',
        slug: 'mentari-mart',
        logo: '/images/top vendors/658b597eb627e280b99c0cf10e482793 2.png',
        rating: 4.5,
        totalRatings: 110,
        deliverySchedule: 'Tomorrow 9:00 AM',
        deliveryTime: '12 hrs',
        minOrderValue: 350,
        creditEnabled: true,
        categories: ['Grocery', 'Vegetables'],
        isActive: true,
        description: 'Grocery & Vegetables marketplace.',
    },
    {
        id: 'v8',
        name: 'Arisha Mart',
        slug: 'arisha-mart',
        logo: '/images/top vendors/ecommerce-logo-template_658705-117 3.png',
        rating: 4.9,
        totalRatings: 1200,
        deliverySchedule: 'Today 8:00 PM',
        deliveryTime: '4 hrs',
        minOrderValue: 500,
        creditEnabled: true,
        categories: ['Everything', 'Grocery'],
        isActive: true,
        description: 'Grocery, Electronics and more.',
    },
    {
        id: 'v9',
        name: 'Allure Mart',
        slug: 'allure-mart',
        logo: '/images/top vendors/da025fadd66fb2aef4d63f0db58b86b5 2.png',
        rating: 4.4,
        totalRatings: 150,
        deliverySchedule: 'Tomorrow 11:00 AM',
        deliveryTime: '24 hrs',
        minOrderValue: 750,
        creditEnabled: false,
        categories: ['Grocery', 'Beauty'],
        isActive: true,
        description: 'Premium grocery and beauty products.',
    },
    {
        id: 'v10',
        name: 'Walmart',
        slug: 'walmart',
        logo: '/images/top vendors/m-mart-grocery-store-brands-logo-238132857 3.png',
        rating: 4.3,
        totalRatings: 85,
        deliverySchedule: 'Tomorrow 7:00 AM',
        deliveryTime: '24 hrs',
        minOrderValue: 600,
        creditEnabled: true,
        categories: ['Grocery', 'Bulk'],
        isActive: true,
        description: 'Grocery and dry fruits center.',
    },
    {
        id: 'v11',
        name: 'Bee Mart',
        slug: 'bee-mart',
        logo: '/images/top vendors/bee-mart.png',
        rating: 4.5,
        totalRatings: 143,
        deliverySchedule: 'Today 6:00 PM',
        deliveryTime: '8 hrs',
        minOrderValue: 400,
        creditEnabled: true,
        creditAmount: 20000,
        categories: ['Dairy', 'Grocery', 'Fresh'],
        isActive: true,
        description: 'Fresh dairy and grocery essentials.',
    },
    {
        id: 'v12',
        name: 'Family Supermarket',
        slug: 'family-supermarket',
        logo: '/images/top vendors/family-supermarket.png',
        rating: 4.6,
        totalRatings: 278,
        deliverySchedule: 'Tomorrow 8:00 AM',
        deliveryTime: '16 hrs',
        minOrderValue: 500,
        creditEnabled: true,
        creditAmount: 35000,
        categories: ['Grocery', 'Household', 'Bulk'],
        isActive: true,
        description: 'Your complete family supermarket.',
    },
    {
        id: 'v13',
        name: 'FreshMart',
        slug: 'freshmart',
        logo: '/images/top vendors/vendor-logo1.png',
        rating: 4.4,
        totalRatings: 195,
        deliverySchedule: 'Today 7:00 PM',
        deliveryTime: '6 hrs',
        minOrderValue: 300,
        creditEnabled: false,
        categories: ['Fruits', 'Vegetables', 'Organic'],
        isActive: true,
        description: 'Farm-fresh fruits and vegetables daily.',
    },
    {
        id: 'v14',
        name: 'SpiceZone',
        slug: 'spicezone',
        logo: '/images/top vendors/vendor-logo2.png',
        rating: 4.7,
        totalRatings: 320,
        deliverySchedule: 'Tomorrow 9:00 AM',
        deliveryTime: '20 hrs',
        minOrderValue: 250,
        creditEnabled: true,
        creditAmount: 10000,
        categories: ['Spices', 'Dry Goods', 'Masala'],
        isActive: true,
        description: 'Premium spices and dry goods supplier.',
    },
    {
        id: 'v15',
        name: 'ColdChain',
        slug: 'coldchain',
        logo: '/images/top vendors/vendor-logo3.png',
        rating: 4.8,
        totalRatings: 410,
        deliverySchedule: 'Today 5:00 PM',
        deliveryTime: '4 hrs',
        minOrderValue: 1000,
        creditEnabled: true,
        creditAmount: 60000,
        categories: ['Frozen', 'Meat', 'Seafood'],
        isActive: true,
        description: 'Cold chain specialists for meat and seafood.',
    },
    {
        id: 'v16',
        name: 'BakeryHub',
        slug: 'bakeryhub',
        logo: '/images/top vendors/vendor-logo4.png',
        rating: 4.5,
        totalRatings: 167,
        deliverySchedule: 'Tomorrow 6:00 AM',
        deliveryTime: '12 hrs',
        minOrderValue: 300,
        creditEnabled: false,
        categories: ['Bakery', 'Bread', 'Pastry'],
        isActive: true,
        description: 'Fresh bakery and artisan bread supplier.',
    },
    {
        id: 'v17',
        name: 'DairyDirect',
        slug: 'dairydirect',
        logo: '/images/top vendors/vendor-logo5.png',
        rating: 4.9,
        totalRatings: 530,
        deliverySchedule: 'Today 4:00 AM',
        deliveryTime: '2 hrs',
        minOrderValue: 200,
        creditEnabled: true,
        creditAmount: 25000,
        categories: ['Dairy', 'Milk', 'Cheese'],
        isActive: true,
        description: 'Direct farm-to-door dairy products.',
    },
    {
        id: 'v18',
        name: 'OilMaster',
        slug: 'oilmaster',
        logo: '/images/top vendors/vendor-logo6.png',
        rating: 4.3,
        totalRatings: 112,
        deliverySchedule: 'Tomorrow 10:00 AM',
        deliveryTime: '24 hrs',
        minOrderValue: 500,
        creditEnabled: true,
        creditAmount: 15000,
        categories: ['Oils', 'Ghee', 'Fats'],
        isActive: true,
        description: 'Edible oils and ghee for HoReCa.',
    },
    {
        id: 'v19',
        name: 'GrainStore',
        slug: 'grainstore',
        logo: '/images/top vendors/vendor-logo7.png',
        rating: 4.6,
        totalRatings: 245,
        deliverySchedule: 'Tomorrow 7:00 AM',
        deliveryTime: '18 hrs',
        minOrderValue: 800,
        creditEnabled: false,
        categories: ['Grains', 'Rice', 'Pulses'],
        isActive: true,
        description: 'Bulk grains, rice, and pulses.',
    },
    {
        id: 'v20',
        name: 'Sharad Dairy',
        slug: 'sharad-dairy',
        logo: '/images/top vendors/vendor-logo8.png',
        rating: 4.7,
        totalRatings: 389,
        deliverySchedule: 'Today 5:00 AM',
        deliveryTime: '3 hrs',
        minOrderValue: 300,
        creditEnabled: true,
        creditAmount: 20000,
        categories: ['Dairy', 'Paneer', 'Milk'],
        isActive: true,
        description: 'Trusted dairy supplier since 1998.',
    },
];

export const MOCK_VENDOR_SUMMARIES: VendorSummary[] = MOCK_VENDORS.map(v => ({
    id: v.id,
    name: v.name,
    slug: v.slug,
    logo: v.logo,
    rating: v.rating,
    deliveryTime: v.deliveryTime,
    minOrderValue: v.minOrderValue,
    creditEnabled: v.creditEnabled,
    categories: v.categories,
}));

// ---- PRODUCTS (PER VENDOR) ----

const productBase = {
    images: ['/images/placeholders/no-product.svg'],
    stock: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
};

export const MOCK_VENDOR_PRODUCTS: Record<string, VendorProduct[]> = {
    v1: [
        { ...productBase, id: 'p1', images: ['/images/category/milk.png'], name: 'Amul Butter', description: 'Pure salted butter', price: 420, originalPrice: 450, category: 'Dairy', subcategory: 'Butter', packSize: '1 kg', unit: 'kg', vendorId: 'v1', vendorName: 'Emarket', bulkPrices: [{ minQty: 5, price: 410 }, { minQty: 10, price: 400 }], creditBadge: true, minOrderQuantity: 1, frequentlyOrdered: true },
        { ...productBase, id: 'p2', images: ['/images/category/dairy.png'], name: 'Amul Cheese Block', description: 'Processed cheese block', price: 380, category: 'Dairy', subcategory: 'Cheese', packSize: '1 kg', unit: 'kg', vendorId: 'v1', vendorName: 'Emarket', bulkPrices: [{ minQty: 5, price: 365 }, { minQty: 10, price: 350 }], creditBadge: true, minOrderQuantity: 1, frequentlyOrdered: true },
        { ...productBase, id: 'p3', images: ['/images/category/milk.png'], name: 'Fresh Paneer', description: 'Farm fresh paneer', price: 320, category: 'Dairy', subcategory: 'Paneer', packSize: '1 kg', unit: 'kg', vendorId: 'v1', vendorName: 'Emarket', bulkPrices: [{ minQty: 5, price: 310 }], creditBadge: true, minOrderQuantity: 1, stock: 0, isActive: false },
        { ...productBase, id: 'p4', images: ['/images/category/milk.png'], name: 'Full Cream Milk', description: 'Full cream pasteurized milk', price: 56, category: 'Dairy', subcategory: 'Milk', packSize: '1 L', unit: 'L', vendorId: 'v1', vendorName: 'Emarket', bulkPrices: [{ minQty: 10, price: 52 }, { minQty: 20, price: 50 }], creditBadge: false, minOrderQuantity: 5 },
        { ...productBase, id: 'p5', images: ['/images/category/dairy.png'], name: 'Mozzarella Cheese', description: 'Shredded mozzarella for pizza', price: 490, category: 'Dairy', subcategory: 'Cheese', packSize: '1 kg', unit: 'kg', vendorId: 'v1', vendorName: 'Emarket', bulkPrices: [{ minQty: 3, price: 470 }], creditBadge: true, minOrderQuantity: 1, isDeal: true },
        { ...productBase, id: 'p6', images: ['/images/category/milk.png'], name: 'Salted Butter Pats', description: 'Individual butter portions', price: 180, category: 'Dairy', subcategory: 'Butter', packSize: '500 g', unit: 'g', vendorId: 'v1', vendorName: 'Emarket', bulkPrices: [], creditBadge: false, minOrderQuantity: 2 },
    ],
    v2: [
        { ...productBase, id: 'p7', images: ['/images/product/product-img1.png'], name: 'Kissan Tomato Ketchup', description: 'Classic tomato ketchup', price: 145, category: 'Sauces', subcategory: 'Ketchup', packSize: '1 kg', unit: 'kg', vendorId: 'v2', vendorName: 'Whole Food Market', bulkPrices: [{ minQty: 5, price: 135 }], creditBadge: true, minOrderQuantity: 1, frequentlyOrdered: true },
        { ...productBase, id: 'p8', images: ['/images/category/oils.png'], name: 'Saffola Gold Oil', description: 'Refined cooking oil', price: 210, category: 'Oils', subcategory: 'Cooking Oil', packSize: '1 L', unit: 'L', vendorId: 'v2', vendorName: 'Whole Food Market', bulkPrices: [{ minQty: 5, price: 200 }, { minQty: 10, price: 190 }], creditBadge: true, minOrderQuantity: 1 },
        { ...productBase, id: 'p9', images: ['/images/category/grains.png'], name: 'Basmati Rice', description: 'Premium long grain basmati', price: 1200, category: 'Grains', subcategory: 'Rice', packSize: '10 kg', unit: 'kg', vendorId: 'v2', vendorName: 'Whole Food Market', bulkPrices: [{ minQty: 3, price: 1150 }], creditBadge: false, minOrderQuantity: 1, frequentlyOrdered: true },
        { ...productBase, id: 'p10', images: ['/images/category/drink-juice.png'], name: 'Soya Sauce', description: 'Dark soya sauce', price: 95, category: 'Sauces', subcategory: 'Asian', packSize: '500 ml', unit: 'ml', vendorId: 'v2', vendorName: 'Whole Food Market', bulkPrices: [], creditBadge: true, minOrderQuantity: 2 },
        { ...productBase, id: 'p11', images: ['/images/category/oils.png'], name: 'Olive Oil Extra Virgin', description: 'Cold pressed olive oil', price: 650, category: 'Oils', subcategory: 'Olive Oil', packSize: '1 L', unit: 'L', vendorId: 'v2', vendorName: 'Whole Food Market', bulkPrices: [{ minQty: 3, price: 620 }], creditBadge: false, minOrderQuantity: 1, isDeal: true, stock: 0, isActive: false },
        { ...productBase, id: 'p12', images: ['/images/category/snacks.png'], name: 'Atta Whole Wheat', description: 'Chakki fresh atta', price: 480, category: 'Grains', subcategory: 'Flour', packSize: '10 kg', unit: 'kg', vendorId: 'v2', vendorName: 'Whole Food Market', bulkPrices: [{ minQty: 5, price: 460 }], creditBadge: true, minOrderQuantity: 1 },
    ],
    v3: [
        { ...productBase, id: 'p13', images: ['/images/placeholders/no-product.svg'], name: 'Fresh Tomatoes', description: 'Farm fresh red tomatoes', price: 40, category: 'Vegetables', subcategory: 'Tomato', packSize: '1 kg', unit: 'kg', vendorId: 'v3', vendorName: 'M Mart', bulkPrices: [{ minQty: 10, price: 35 }], creditBadge: false, minOrderQuantity: 2, frequentlyOrdered: true },
        { ...productBase, id: 'p14', images: ['/images/product/product-img5.png'], name: 'Onions', description: 'Premium quality onions', price: 35, category: 'Vegetables', subcategory: 'Onion', packSize: '1 kg', unit: 'kg', vendorId: 'v3', vendorName: 'M Mart', bulkPrices: [{ minQty: 10, price: 30 }], creditBadge: false, minOrderQuantity: 5, stock: 0, isActive: false },
        { ...productBase, id: 'p15', images: ['/images/placeholders/no-product.svg'], name: 'Green Capsicum', description: 'Fresh green bell peppers', price: 80, category: 'Vegetables', subcategory: 'Capsicum', packSize: '1 kg', unit: 'kg', vendorId: 'v3', vendorName: 'M Mart', bulkPrices: [], creditBadge: false, minOrderQuantity: 1, frequentlyOrdered: true },
        { ...productBase, id: 'p16', images: ['/images/product/brokali.png'], name: 'Fresh Coriander', description: 'Bunch of fresh coriander', price: 15, category: 'Herbs', subcategory: 'Coriander', packSize: '100 g', unit: 'g', vendorId: 'v3', vendorName: 'M Mart', bulkPrices: [], creditBadge: false, minOrderQuantity: 5 },
    ],
    v4: [
        { ...productBase, id: 'p17', images: ['/images/category/milk.png'], name: 'Gokul Paneer', description: 'Soft fresh paneer', price: 300, category: 'Dairy', subcategory: 'Paneer', packSize: '1 kg', unit: 'kg', vendorId: 'v4', vendorName: 'Groceri', bulkPrices: [{ minQty: 5, price: 285 }], creditBadge: true, minOrderQuantity: 1, frequentlyOrdered: true },
        { ...productBase, id: 'p18', images: ['/images/category/dairy.png'], name: 'Gokul Curd', description: 'Fresh set curd', price: 45, category: 'Dairy', subcategory: 'Curd', packSize: '1 kg', unit: 'kg', vendorId: 'v4', vendorName: 'Groceri', bulkPrices: [{ minQty: 10, price: 40 }], creditBadge: true, minOrderQuantity: 2 },
    ],
    v5: [
        { ...productBase, id: 'p19', images: ['/images/category/spices.png'], name: 'Red Chilli Powder', description: 'Kashmiri red chilli', price: 350, category: 'Spices', subcategory: 'Chilli', packSize: '500 g', unit: 'g', vendorId: 'v5', vendorName: 'Borcelle', bulkPrices: [{ minQty: 5, price: 330 }], creditBadge: false, minOrderQuantity: 1, frequentlyOrdered: true },
        { ...productBase, id: 'p20', images: ['/images/category/grains.png'], name: 'Turmeric Powder', description: 'Pure haldi powder', price: 280, category: 'Spices', subcategory: 'Turmeric', packSize: '500 g', unit: 'g', vendorId: 'v5', vendorName: 'Borcelle', bulkPrices: [{ minQty: 5, price: 265 }], creditBadge: false, minOrderQuantity: 1 },
        { ...productBase, id: 'p21', images: ['/images/category/drink-juice.png'], name: 'Garam Masala', description: 'Whole spice blend', price: 420, category: 'Masalas', subcategory: 'Blends', packSize: '500 g', unit: 'g', vendorId: 'v5', vendorName: 'Borcelle', bulkPrices: [], creditBadge: false, minOrderQuantity: 1, isDeal: true },
    ],
    v6: [
        { ...productBase, id: 'p22', images: ['/images/category/snacks.png'], name: 'Maida (Refined Flour)', description: 'Fine maida for baking', price: 320, category: 'Bakery', subcategory: 'Flour', packSize: '10 kg', unit: 'kg', vendorId: 'v6', vendorName: 'Cartomart', bulkPrices: [{ minQty: 5, price: 300 }], creditBadge: true, minOrderQuantity: 1, frequentlyOrdered: true },
        { ...productBase, id: 'p23', images: ['/images/category/candy.png'], name: 'Dark Chocolate Couverture', description: '70% dark chocolate', price: 850, category: 'Bakery', subcategory: 'Chocolate', packSize: '1 kg', unit: 'kg', vendorId: 'v6', vendorName: 'Cartomart', bulkPrices: [{ minQty: 3, price: 810 }], creditBadge: true, minOrderQuantity: 1, isDeal: true, stock: 0, isActive: false },
        { ...productBase, id: 'p24', images: ['/images/category/desset.png'], name: 'Vanilla Essence', description: 'Pure vanilla extract', price: 180, category: 'Bakery', subcategory: 'Essences', packSize: '500 ml', unit: 'ml', vendorId: 'v6', vendorName: 'Cartomart', bulkPrices: [], creditBadge: false, minOrderQuantity: 1 },
    ],
};


// ---- ALL PRODUCTS FLAT (for search) ----

export const ALL_MOCK_PRODUCTS: VendorProduct[] = Object.values(MOCK_VENDOR_PRODUCTS).flat();

// ---- CATEGORIES ----

export const MOCK_CATEGORIES: Category[] = [
    { id: 'c1', name: 'Dairy', slug: 'dairy', image: '/images/category/dairy.png', icon: '🧀', itemCount: 24, isActive: true },
    { id: 'c2', name: 'Vegetables', slug: 'vegetables', image: '/images/category/vegetables.png', icon: '🥬', itemCount: 18, isActive: true },
    { id: 'c3', name: 'Fruits', slug: 'fruits', image: '/images/category/fruits.png', icon: '🍎', itemCount: 12, isActive: true },
    { id: 'c4', name: 'Grocery', slug: 'grocery', image: '/images/category/grocery.png', icon: '🛒', itemCount: 45, isActive: true },
    { id: 'c5', name: 'Sauces & Condiments', slug: 'sauces-condiments', image: '/images/category/sauces.png', icon: '🫙', itemCount: 15, isActive: true },
    { id: 'c6', name: 'Oils', slug: 'oils', image: '/images/category/oils.png', icon: '🫒', itemCount: 8, isActive: true },
    { id: 'c7', name: 'Spices & Masalas', slug: 'spices-masalas', image: '/images/category/spices.png', icon: '🌶️', itemCount: 22, isActive: true },
    { id: 'c8', name: 'Bakery Ingredients', slug: 'bakery-ingredients', image: '/images/category/bakery.png', icon: '🍰', itemCount: 14, isActive: true },
    { id: 'c9', name: 'Grains & Flour', slug: 'grains-flour', image: '/images/category/grains.png', icon: '🌾', itemCount: 10, isActive: true },
    { id: 'c10', name: 'Beverages', slug: 'beverages', image: '/images/category/beverages.png', icon: '🧃', itemCount: 8, isActive: true },
];

// ---- ORDER LISTS ----

export const MOCK_ORDER_LISTS: OrderList[] = [
    {
        id: 'ol1',
        name: 'Daily Kitchen Supplies',
        userId: 'u1',
        vendorId: 'v6',
        vendorName: 'Cartomart',
        vendorLogo: '/images/top vendors/39a5dd37096e44eb8b72e053055e32896d63c44a.png',
        items: [
            { productId: 'p22', product: { ...MOCK_VENDOR_PRODUCTS.v6[0], vendorLogo: '/images/top vendors/39a5dd37096e44eb8b72e053055e32896d63c44a.png' }, defaultQty: 5, lastOrderedQty: 5 },
            { productId: 'p23', product: { ...MOCK_VENDOR_PRODUCTS.v6[1], vendorLogo: '/images/top vendors/39a5dd37096e44eb8b72e053055e32896d63c44a.png' }, defaultQty: 1, lastOrderedQty: 1 },
            { productId: 'p24', product: { ...MOCK_VENDOR_PRODUCTS.v6[0], vendorLogo: '/images/top vendors/39a5dd37096e44eb8b72e053055e32896d63c44a.png' }, defaultQty: 2, lastOrderedQty: 2 },
        ],
        createdAt: new Date('2026-02-15'),
        updatedAt: new Date('2026-03-10'),
        lastUsed: new Date('2026-03-10'),
    },
    {
        id: 'ol2',
        name: 'Weekly Grocery',
        userId: 'u1',
        vendorId: 'v4',
        vendorName: 'Groceri',
        vendorLogo: '/images/top vendors/groceri.png',
        items: [
            { productId: 'p17', product: MOCK_VENDOR_PRODUCTS.v4[0], defaultQty: 3, lastOrderedQty: 3 },
            { productId: 'p18', product: MOCK_VENDOR_PRODUCTS.v4[1], defaultQty: 5, lastOrderedQty: 5 },
        ],
        createdAt: new Date('2026-02-20'),
        updatedAt: new Date('2026-03-08'),
        lastUsed: new Date('2026-03-08'),
    },
    {
        id: 'ol3',
        name: 'Inventory Restock',
        userId: 'u1',
        vendorId: 'v1',
        vendorName: 'Emarket',
        vendorLogo: '/images/placeholders/no-vendor.svg',
        items: [
            { productId: 'p1', product: MOCK_VENDOR_PRODUCTS.v1[0], defaultQty: 10, lastOrderedQty: 10 },
            { productId: 'p2', product: MOCK_VENDOR_PRODUCTS.v1[1], defaultQty: 5, lastOrderedQty: 5 },
        ],
        createdAt: new Date('2026-03-01'),
        updatedAt: new Date('2026-03-12'),
        lastUsed: new Date('2026-03-12'),
    },
    {
        id: 'ol4',
        name: 'Organic Supplies',
        userId: 'u1',
        vendorId: 'v2',
        vendorName: 'Whole Food Market',
        vendorLogo: '/images/top vendors/whole-foods-market.png',
        items: [
            { productId: 'p4', product: MOCK_VENDOR_PRODUCTS.v2[0], defaultQty: 4, lastOrderedQty: 4 },
            { productId: 'p5', product: MOCK_VENDOR_PRODUCTS.v2[1], defaultQty: 6, lastOrderedQty: 6 },
        ],
        createdAt: new Date('2026-03-05'),
        updatedAt: new Date('2026-03-14'),
        lastUsed: new Date('2026-03-14'),
    },
    {
        id: 'ol5',
        name: 'Daily Essentials',
        userId: 'u1',
        vendorId: 'v3',
        vendorName: 'M Mart',
        vendorLogo: '/images/top vendors/m-mart.png',
        items: [
            { productId: 'p8', product: MOCK_VENDOR_PRODUCTS.v3[0], defaultQty: 2, lastOrderedQty: 2 },
            { productId: 'p9', product: MOCK_VENDOR_PRODUCTS.v3[1], defaultQty: 8, lastOrderedQty: 8 },
        ],
        createdAt: new Date('2026-03-08'),
        updatedAt: new Date('2026-03-15'),
        lastUsed: new Date('2026-03-15'),
    },
    {
        id: 'ol6',
        name: 'Borcelle Special',
        userId: 'u1',
        vendorId: 'v5',
        vendorName: 'Borcelle',
        vendorLogo: '/images/top vendors/961d17c25868145dd167df9f88ca0d40a7c057d1.png',
        items: [
            { productId: 'p20', product: MOCK_VENDOR_PRODUCTS.v5[0], defaultQty: 5, lastOrderedQty: 5 },
        ],
        createdAt: new Date('2026-03-10'),
        updatedAt: new Date('2026-03-16'),
        lastUsed: new Date('2026-03-16'),
    },
];

// ---- PAST ORDERS ----

export const MOCK_PAST_ORDERS: PurchaseOrder[] = [
    {
        id: 'PO-2026-001',
        vendorId: 'v1',
        vendorName: 'Emarket',
        vendorLogo: '/images/top vendors/vendor-logo1.png',
        userId: 'u1',
        items: [
            { productId: 'p1', name: 'Amul Butter', packSize: '1 kg', price: 420, quantity: 2, total: 840 },
            { productId: 'p2', name: 'Amul Cheese Block', packSize: '1 kg', price: 380, quantity: 1, total: 380 },
            { productId: 'p3', name: 'Fresh Paneer', packSize: '1 kg', price: 320, quantity: 3, total: 960 },
        ],
        subtotal: 2180,
        tax: 0,
        deliveryCharge: 0,
        total: 2180,
        status: 'delivered',
        paymentMethod: 'credit',
        paymentStatus: 'paid',
        deliverySchedule: '10 Mar 2026, 7:00 AM',
        createdAt: new Date('2026-03-09'),
        updatedAt: new Date('2026-03-10'),
    },
    {
        id: 'PO-2026-002',
        vendorId: 'v2',
        vendorName: 'Whole Food Market',
        vendorLogo: '/images/top vendors/vendor-logo2.png',
        userId: 'u1',
        items: [
            { productId: 'p7', name: 'Kissan Tomato Ketchup', packSize: '1 kg', price: 145, quantity: 3, total: 435 },
            { productId: 'p9', name: 'Basmati Rice', packSize: '10 kg', price: 1200, quantity: 2, total: 2400 },
        ],
        subtotal: 2835,
        tax: 0,
        deliveryCharge: 0,
        total: 2835,
        status: 'confirmed',
        paymentMethod: 'online',
        paymentStatus: 'paid',
        deliverySchedule: '12 Mar 2026, 6:00 AM',
        createdAt: new Date('2026-03-11'),
        updatedAt: new Date('2026-03-11'),
    },
];

// ---- COLLECTIONS ----

export const MOCK_COLLECTIONS = [
    { id: 'col1', name: 'Italian Kitchen', icon: '🇮🇹', description: 'Everything for pasta, pizza & more', slug: 'italian-kitchen', color: '#FEF3C7' },
    { id: 'col2', name: 'Oriental Kitchen', icon: '🥢', description: 'Wok-ready sauces, noodles & spices', slug: 'oriental-kitchen', color: '#FEE2E2' },
    { id: 'col3', name: 'Ready to Cook', icon: '⚡', description: 'Pre-made mixes & instant items', slug: 'ready-to-cook', color: '#DBEAFE' },
    { id: 'col4', name: 'Heavy Discounts', icon: '🏷️', description: 'Best wholesale deals this week', slug: 'heavy-discounts', color: '#D1FAE5' },
    { id: 'col5', name: 'Bakery Essentials', icon: '🧁', description: 'Flour, chocolate, cream & more', slug: 'bakery-essentials', color: '#FCE7F3' },
    { id: 'col6', name: 'Tandoor & Grill', icon: '🔥', description: 'Marinades, charcoal & tandoor items', slug: 'tandoor-grill', color: '#FED7AA' },
];

// ---- BRAND STORES ----

export const BRAND_STORE_DATA: Record<string, BrandStore> = {
    'kitchen-smith': {
        id: 'kitchen-smith',
        name: 'Kitchen Smith',
        bannerImage: '/images/brand/kitchen-smith-banner.png',
        logo: '/images/brand/03b885b1-5477-4aa9-af03-d948165745e61771835977.png',
        productCount: 12,
        products: [
            { id: 'ks-1', name: 'Kitchen Smith All Purpose Flour 1kg', image: '/images/shope by brand/brand-img1.png', category: 'Flour & Grains' },
            { id: 'ks-2', name: 'Kitchen Smith Basmati Rice 5kg', image: '/images/shope by brand/brand-img2.png', category: 'Rice & Grains' },
            { id: 'ks-3', name: 'Kitchen Smith Turmeric Powder 500g', image: '/images/shope by brand/brand-img3.png', category: 'Spices' },
            { id: 'ks-4', name: 'Kitchen Smith Chili Powder 250g', image: '/images/shope by brand/brand-img4.png', category: 'Spices' },
            { id: 'ks-5', name: 'Kitchen Smith Cumin Seeds 100g', image: '/images/shope by brand/brand-img1.png', category: 'Spices' },
            { id: 'ks-6', name: 'Kitchen Smith Black Pepper 100g', image: '/images/shope by brand/brand-img2.png', category: 'Spices' },
            { id: 'ks-7', name: 'Kitchen Smith Coriander Powder 250g', image: '/images/shope by brand/brand-img3.png', category: 'Spices' },
            { id: 'ks-8', name: 'Kitchen Smith Garam Masala 100g', image: '/images/shope by brand/brand-img4.png', category: 'Spices' },
            { id: 'ks-9', name: 'Kitchen Smith Mustard Seeds 100g', image: '/images/shope by brand/brand-img1.png', category: 'Spices' },
            { id: 'ks-10', name: 'Kitchen Smith Fenugreek Seeds 100g', image: '/images/shope by brand/brand-img2.png', category: 'Spices' },
        ],
        vendors: [
            {
                id: 'v1',
                name: 'Emarket',
                logo: '/images/placeholders/no-vendor.svg',
                location: 'Mumbai',
                productIds: ['ks-1', 'ks-2', 'ks-3', 'ks-4', 'ks-5'],
                prices: { 'ks-1': '120', 'ks-2': '450', 'ks-3': '85', 'ks-4': '95', 'ks-5': '110' },
            },
            {
                id: 'v2',
                name: 'Whole Food Market',
                logo: '/images/top vendors/whole-foods-market.png',
                location: 'Mumbai',
                productIds: ['ks-1', 'ks-2', 'ks-3', 'ks-6', 'ks-7', 'ks-8'],
                prices: { 'ks-1': '125', 'ks-2': '480', 'ks-3': '90', 'ks-6': '120', 'ks-7': '100', 'ks-8': '140' },
            },
            {
                id: 'v3',
                name: 'M Mart',
                logo: '/images/top vendors/m-mart.png',
                location: 'Mumbai',
                productIds: ['ks-2', 'ks-3', 'ks-4', 'ks-5', 'ks-9', 'ks-10'],
                prices: { 'ks-2': '440', 'ks-3': '80', 'ks-4': '90', 'ks-5': '105', 'ks-9': '115', 'ks-10': '125' },
            },
        ],
    },
    'kissan': {
        id: 'kissan',
        name: 'Kissan',
        bannerImage: '/images/brand/kissan-banner.png',
        logo: '/images/brand/dc458c67-3702-4da8-8cb8-8011f0d3e17a1767094486.png',
        productCount: 10,
        products: [
            { id: 'k-1', name: 'Kissan Tomato Ketchup 1kg', image: '/images/shope by brand/brand-img4.png', category: 'Condiments' },
            { id: 'k-2', name: 'Kissan Chilli Sauce 500g', image: '/images/shope by brand/brand-img1.png', category: 'Condiments' },
            { id: 'k-3', name: 'Kissan Mango Pickle 500g', image: '/images/shope by brand/brand-img2.png', category: 'Pickles' },
            { id: 'k-4', name: 'Kissan Mixed Pickle 500g', image: '/images/shope by brand/brand-img3.png', category: 'Pickles' },
            { id: 'k-5', name: 'Kissan Lime Pickle 500g', image: '/images/shope by brand/brand-img4.png', category: 'Pickles' },
            { id: 'k-6', name: 'Kissan Strawberry Jam 500g', image: '/images/shope by brand/brand-img1.png', category: 'Spreads' },
            { id: 'k-7', name: 'Kissan Mango Pulp 1kg', image: '/images/shope by brand/brand-img2.png', category: 'Pulps' },
            { id: 'k-8', name: 'Kissan Pineapple Jam 500g', image: '/images/shope by brand/brand-img3.png', category: 'Spreads' },
            { id: 'k-9', name: 'Kissan Tomato Sauce 1kg', image: '/images/shope by brand/brand-img4.png', category: 'Condiments' },
        ],
        vendors: [
            {
                id: 'v1',
                name: 'Emarket',
                logo: '/images/placeholders/no-vendor.svg',
                location: 'Mumbai',
                productIds: ['k-1', 'k-2', 'k-3', 'k-4'],
                prices: { 'k-1': '180', 'k-2': '150', 'k-3': '120', 'k-4': '130' },
            },
            {
                id: 'v2',
                name: 'Whole Food Market',
                logo: '/images/top vendors/whole-foods-market.png',
                location: 'Mumbai',
                productIds: ['k-1', 'k-3', 'k-5', 'k-6', 'k-7'],
                prices: { 'k-1': '190', 'k-3': '125', 'k-5': '135', 'k-6': '160', 'k-7': '220' },
            },
            {
                id: 'v3',
                name: 'M Mart',
                logo: '/images/top vendors/m-mart.png',
                location: 'Mumbai',
                productIds: ['k-2', 'k-4', 'k-7', 'k-8', 'k-9'],
                prices: { 'k-2': '145', 'k-4': '125', 'k-7': '210', 'k-8': '155', 'k-9': '200' },
            },
        ],
    },
};
